layerfolders:
  - "resources/input/Default/Skin"
  - "resources/input/Default/Eyes"
  - "resources/input/Default/Mouth"
  # optionals
  - "resources/input/Clothes"
  - "resources/input/Hair"

# the percentage of the generated pictures to save
desiredpicturesnumber: 980

outputfolder: "resources/output"